# Generated by Django 5.2.2 on 2025-06-09 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.cliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('cpf', models.CharField(max_length=14)),
                ('identidade', models.CharField(max_length=20)),
                ('data_expedicao', models.DateField()),
                ('orgao_emissor', models.CharField(max_length=20)),
                ('uf_identidade', models.CharField(max_length=2)),
                ('data_nascimento', models.DateField()),
                ('pais', models.CharField(max_length=50)),
                ('titulo_eleitor', models.CharField(max_length=20)),
                ('profissao', models.CharField(max_length=50)),
                ('outra_profissao', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone1', models.CharField(max_length=20)),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('nome_mae', models.CharField(max_length=150)),
                ('nome_pai', models.CharField(blank=True, max_length=150, null=True)),
                ('cep_residencial', models.CharField(max_length=9)),
                ('endereco_residencial', models.CharField(max_length=255)),
                ('numero_residencial', models.CharField(max_length=10)),
                ('bairro_residencial', models.CharField(max_length=100)),
                ('cidade_residencial', models.CharField(max_length=100)),
                ('uf_residencial', models.CharField(max_length=2)),
                ('complemento_residencial', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude_residencial', models.CharField(blank=True, max_length=30, null=True)),
                ('longitude_residencial', models.CharField(blank=True, max_length=30, null=True)),
                ('cep_acervo', models.CharField(blank=True, max_length=9, null=True)),
                ('endereco_acervo', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_acervo', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro_acervo', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade_acervo', models.CharField(blank=True, max_length=100, null=True)),
                ('uf_acervo', models.CharField(blank=True, max_length=2, null=True)),
                ('complemento_acervo', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude_acervo', models.CharField(blank=True, max_length=30, null=True)),
                ('longitude_acervo', models.CharField(blank=True, max_length=30, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'cpf')},
            },
        ),
    ]
